# Import dependencies

In [4]:
!pip install ffmpeg
!pip install pyvirtualdisplay
!pip install stable-baselines3[extra]

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6090 sha256=16a39bfece5e169f6854f0f506faa147c99473c36fef3f261014ed563c14f94a
  Stored in directory: c:\users\william.mendes\appdata\local\pip\cache\wheels\1d\57\24\4eff6a03a9ea0e647568e8a5a0546cdf957e3cf005372c0245
Successfully built ffmpeg


In [5]:
!pip install atari_py

In [6]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

Looking in indexes: https://download.pytorch.org/whl/cu117


In [7]:
import os
import numpy as np
import gymnasium as gym
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env

# Test enviroment

http://www.atarimania.com/roms/Roms.rar

Create a folder named Atari

In [8]:
!python -m atari_py.import_roms ./ROMS

copying adventure.bin from ./ROMS\Adventure (1980) (Atari, Warren Robinett) (CX2613, CX2613P) (PAL).bin to c:\Users\william.mendes\Anaconda3\lib\site-packages\atari_py\atari_roms\adventure.bin
copying air_raid.bin from ./ROMS\Air Raid (1982) (Men-A-Vision) (PAL) ~.bin to c:\Users\william.mendes\Anaconda3\lib\site-packages\atari_py\atari_roms\air_raid.bin
copying alien.bin from ./ROMS\Alien (1982) (20th Century Fox Video Games, Douglas 'Dallas North' Neubauer) (11006) ~.bin to c:\Users\william.mendes\Anaconda3\lib\site-packages\atari_py\atari_roms\alien.bin
copying amidar.bin from ./ROMS\Amidar (1982) (Parker Brothers, Ed Temple) (PB5310) ~.bin to c:\Users\william.mendes\Anaconda3\lib\site-packages\atari_py\atari_roms\amidar.bin
copying assault.bin from ./ROMS\Assault (AKA Sky Alien) (1983) (Bomb - Onbase) (CA281).bin to c:\Users\william.mendes\Anaconda3\lib\site-packages\atari_py\atari_roms\assault.bin
copying asterix.bin from ./ROMS\Asterix (AKA Taz) (1984) (Atari, Jerome Domurat, Ste

In [9]:
enviroment_name = 'Breakout-v4'
env = gym.make(enviroment_name, render_mode='human')

In [10]:
env.reset()

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 {'lives': 5, 'episode_frame_number': 0, 'frame_number': 0})

In [11]:
env.action_space

Discrete(4)

In [12]:
env.observation_space

Box(0, 255, (210, 160, 3), uint8)

In [13]:
episodes = 5
for episode in range(1, episodes+1):
  obs = env.reset()
  done = False
  score = 0

  while not done:
    env.render()
    action = env.action_space.sample()
    obs, reward, done, truncated, info = env.step(action)
    score += reward

  print('Episode: {} Score {}'.format(episode, score))
#env.close()

c:\Users\william.mendes\Anaconda3\lib\site-packages\gymnasium\utils\passive_env_checker.py:364: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(


Episode: 1 Score 2.0
Episode: 2 Score 3.0
Episode: 3 Score 1.0
Episode: 4 Score 0.0
Episode: 5 Score 1.0


In [14]:
env.close()

# Vectorize enviroment and train model

Vectorizing the enviroment, particulary with multiple enviroments, allows to train the agent faster by training in parallel

In [30]:
env = make_atari_env('Breakout-v4', n_envs=4, seed=0)
env = VecFrameStack(env, n_stack=4)

In [16]:
env.reset()

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        ...,

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0

In [17]:
env.render()

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [18]:
env.close()

In [33]:
log_path = os.path.join('Training', 'Logs')
model = A2C('CnnPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env in a VecTransposeImage.


In [21]:
model.learn(total_timesteps=100000)

Logging to Training\Logs\A2C_1
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 268      |
|    ep_rew_mean        | 1.34     |
| time/                 |          |
|    fps                | 110      |
|    iterations         | 100      |
|    time_elapsed       | 18       |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -1.39    |
|    explained_variance | 0.151    |
|    learning_rate      | 0.0007   |
|    n_updates          | 99       |
|    policy_loss        | 0.33     |
|    value_loss         | 0.308    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 271      |
|    ep_rew_mean        | 1.37     |
| time/                 |          |
|    fps                | 103      |
|    iterations         | 200      |
|    time_elapsed       | 38       |
|    total_timesteps    | 4000     |
| train

In [34]:
model.learn(total_timesteps=2000000)

Logging to Training\Logs\A2C_2
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 260      |
|    ep_rew_mean        | 1.12     |
| time/                 |          |
|    fps                | 98       |
|    iterations         | 100      |
|    time_elapsed       | 20       |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -1.38    |
|    explained_variance | 0.0441   |
|    learning_rate      | 0.0007   |
|    n_updates          | 99       |
|    policy_loss        | 0.0278   |
|    value_loss         | 0.0595   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 276      |
|    ep_rew_mean        | 1.49     |
| time/                 |          |
|    fps                | 96       |
|    iterations         | 200      |
|    time_elapsed       | 41       |
|    total_timesteps    | 4000     |
| train

# Save and reload model

In [37]:
a2c_path = os.path.join('Training', 'Saved models', 'A2C_Breakout_2M_Model')
model.save(a2c_path)

In [38]:
del model

In [39]:
a2c_path = os.path.join('Training', 'Saved models', 'A2C_Breakout_2M_model')

In [40]:
model = A2C.load(a2c_path, env)

Wrapping the env in a VecTransposeImage.


# Evaluate and test

In [41]:
env = make_atari_env('Breakout-v4', n_envs=1, seed=0)
env = VecFrameStack(env, n_stack=4)

In [42]:
evaluate_policy(model, env, n_eval_episodes=50, render=True)

(21.08, 7.583772148475981)

In [27]:
env.close()